### ISSUE TITLE
Auth Failing

### ISSUE THREAD

**Issue by RohanAdwankar** [dpeachpeach/kalshi-rust#15]
# Login deserialization error

## Issue
The crate fails to handle API error responses during login attempts, trying to deserialize error responses as successful ones containing `member_id`.

## Reproduction
```rust
let mut kalshi_instance = Kalshi::new(TradingEnvironment::DemoMode);
let result = kalshi_instance.login("test@example.com", "password").await;
```

Error received:
```
RequestError(SerializationError(reqwest::Error { kind: Decode, source: Error("missing field `member_id`", line: 1, column: 89) }))
```

The API returns a valid error response:
```json
{
    "error": {
        "code": "invalid_credentials",
        "message": "invalid credentials",
        "service": "auth"
    }
}
```

## Next Steps / Question
Certainly, it would be an improvement to add proper handling for invalid credentials but I wanted to check if anyone is able to properly authenticate? Even outside of the create all my requests are met with 401s.

**Comment by dpeachpeach** [comment]
Hi Rohan.

Thanks for posting the issue!

I haven't used the API in a few months but I wrote my own private 'testing bot' a while back that ran through a bunch of kalshi-rust API calls and I just ran it and it still seems to be authenticating properly. 

Is it possible that you are using the credentials of a non-demo account when you're calling Kalshi:new(TradingEnvironment::Demode);? Your kalshi account is non-demo by default. If you're using non-demo credentials with a demo argument that could be the case.

If this isn't the case please follow up, I'd be happy to help sort this out.

**Comment by RohanAdwankar** [comment]
Hello, thanks for the quick response!
Thanks for catching that, though when I switch to LiveMarketMode it doesn't seem to be working either. Here is my current code where I tried doing it manually and doing it via the crate:
```
use kalshi::{Kalshi, TradingEnvironment};
use tokio;

#[tokio::main(flavor = "multi_thread")]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let email = "<email>";
    let password = "<password>";

    //doing it manually
    println!("\nAttempting to login manually...");
    let client = reqwest::Client::new();
    let base_url = "https://api.elections.kalshi.com/trade-api/v2";
    let raw_response = client
        .post(format!("{}/login", base_url))
        .json(&serde_json::json!({
            "email": email,
            "password": password
        }))
        .send()
        .await?;
    println!("Raw response status: {}", raw_response.status());
    let response_text = raw_response.text().await?;
    println!("Raw response body: {}", response_text);

    //through crate
    let mut kalshi_instance = Kalshi::new(TradingEnvironment::LiveMarketMode);
    println!("\nAttempting to login through kalshi crate...");
    match kalshi_instance.login(email, password).await {
        Ok(response) => {
            println!("Login successful!");
            println!("Response: {:?}", response);
        }
        Err(e) => {
            println!("Login error details: {:?}", e);
            return Err(e.into());
        }
    }

    Ok(())
}
```
After cargo run I get back:
```
Attempting to login manually...
Raw response status: 400 Bad Request
Raw response body: null

Attempting to login through kalshi crate...
Login error details: RequestError(SerializationError(reqwest::Error { kind: Decode, source: Error("missing field `member_id`", line: 1, column: 89) }))
Error: RequestError(SerializationError(reqwest::Error { kind: Decode, source: Error("missing field `member_id`", line: 1, column: 89) }))
```
I did double-check that the credentials are correct so I am not sure why neither seems to be working. I would appreciate if you catch something or even if you could provide a snippet of how you got it working!

**Comment by dpeachpeach** [comment]
Hi Rohan!

Here's the code for the script that authenticates properly on my machine. (I modified it slightly to remove the references to out of date tickers and focus on authentication on my machine.)

https://github.com/dpeachpeach/kalshi-rust/blob/main/sample_bot/src/main.rs

There's a helper defined that retrieves credentials from a local .env file. I suggest using a .env vs. storing your credentials in plaintext if you plan to share your code with anybody.

This is the modified file that works out of the box for authentication on my machine.

```rust
use dotenv::dotenv;
use kalshi::Kalshi;
use std::env;

extern crate kalshi;

enum APIType {
    Live,
    Demo,
}

fn retreive_credentials(setting: APIType) -> Result<(String, String), std::io::Error> {
    let mut password: String = "dummy".to_string();
    let mut username: String = "dummy".to_string();
    match setting {
        APIType::Live => {
            if let Ok(key) = env::var("LIVE_PASSWORD") {
                println!("got password");
                password = key;
            }
            if let Ok(user) = env::var("LIVE_USER_NAME") {
                println!("got user");
                username = user;
            }
        }

        APIType::Demo => {
            if let Ok(key) = env::var("DEMO_PASSWORD") {
                println!("got password");
                password = key;
            }
            if let Ok(user) = env::var("DEMO_USER_NAME") {
                println!("got user");
                username = user;
            }
        }
    }
    Ok((username, password))
}
#[tokio::main]
async fn main() {
    dotenv().ok();

    let (username, password) = retreive_credentials(APIType::Demo).unwrap();

    let mut kalshi_instance = Kalshi::new(kalshi::TradingEnvironment::DemoMode);

    let login_response = kalshi_instance.login(&username, &password).await;

    match login_response {
        Ok(response) => {
            println!("Login Successful!");
            println!("Response: {:?}", response);
        }
        Err(e) => {
            println!("Login failed");
            println!("Response: {:?}", e);
        }
    }

    /*

    let new_york_ticker = "HIGHNY-23NOV13-T51".to_string();

    let nytemp_market_data = kalshi_instance.get_single_market(&new_york_ticker).await.unwrap();

    let nytemp_market_orderbook = kalshi_instance.get_market_orderbook(&new_york_ticker, Some(1)).await.unwrap();


      let bought_order = kalshi_instance
        .create_order(
            kalshi::Action::Buy,
            None,
            1,
            kalshi::Side::Yes,
            new_york_ticker,
            kalshi::OrderType::Limit,
            None,
            None,
            None,
            None,
            Some(5),
        )
        .await
        .unwrap();

    let ny_order_id = bought_order.order_id.clone();

    let cancelled_order = kalshi_instance.cancel_order(&ny_order_id).await.unwrap();
    println!("{:?}", cancelled_order);

    */
    println!("Sample Success!");
}
```

If this doesn't work I'm not sure what the problem could be but I could take a deeper dive into their direct REST API docs to see if they changed anything in regards to auth. (But it should be backwards compatible anyways if they did, so I wouldn't know what the specific issue in this case would be)

Please let me know if this works after defining a .env file with your credentials. 

Thanks!
David

Output for running this on my demo account:
```
got password
got user
Login Successful!
Response: ()
Sample Success!
```

(Login as it works right now should return a unit type, that's just the way I designed login() back then. Maybe I should include the request details :p)

**Comment by dpeachpeach** [comment]
Oh I just reread your post:

```
Attempting to login manually...
Raw response status: 400 Bad Request
Raw response body: null

Attempting to login through kalshi crate...
Login error details: RequestError(SerializationError(reqwest::Error { kind: Decode, source: Error("missing field `member_id`", line: 1, column: 89) }))
Error: RequestError(SerializationError(reqwest::Error { kind: Decode, source: Error("missing field `member_id`", line: 1, column: 89) }))
```

400 signifies an issue with the arguments you're feeding to their API. It might be possible that the way you're inputting your credentials is improper? Have you made sure they match your login credentials exactly? They're case sensitive.

https://trading-api.readme.io/reference/login

For an issue like this I would suggest reaching out to the kalshi devs on their discord server. I hope you can figure this out! 

Thanks,
David

**Comment by RohanAdwankar** [comment]
Hey David thanks again for all your help!
I think the issue is likely related to the account / auth credentials rather than the package itself, so I will close the Issue now and work with the account holder / Kalshi to get it working.
