### ISSUE TITLE
`get_multiple_orders` doesn't return `Option<String>`

### ISSUE THREAD

**Issue by matteosantama** [dpeachpeach/kalshi-rust#6]
`Kalshi::get_multiple_orders` returns the cursor for pagination and a vector of orders. The cursor is represented by `Option<String>`. The Kalshi API, however, does not seem to make the `cursor` field optional. For example, for an account with no resting orders the API returns

```json
{"orders":[],"cursor":""}
```

`get_multiple_orders` then returns `Some("")` for the cursor. I think `"cursor": ""` should be serialized into `None`. If this is agreeable, I will open a PR

**Comment by dpeachpeach** [comment]
Hey matteo,

Awesome suggestion! This is a great way to make the API more ironclad. Feel free to open a PR, I can review it sometime this weekend.
